dist: trusty

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache:
  directories:
     - ./node_modules

install:
  - npm install

before_script:
  - cp src/environments/environment.travis.ts src/environments/environment.ts

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
